
apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: quarkus-openapi-template
  title: Create a Quarkus Backend application from an OpenApi
  description: Create a starter Quarkus Backend application from an OpenApi
  tags:
    - quarkus
    - java
    - maven
    - s2i-java
    - openapi
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOrganizations:
              - thio-jgmpn

    - title: Choose an API
      required:
        - nameApi
      properties:
        nameApi:
          title: API name
          type: string
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              kind:
                - API



  steps:
    - id: fetch-catalog-api
      name: Fetch API info
      action: catalog:fetch
      input:
        entityRef: ${{parameters.nameApi}}


    - id: template
      name: Generating the Source Code Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{parameters.name}}
          owner: ${{parameters.owner}}
          organization: ${{parameters.organization}}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: debug-log
      name: debug-log
      action: debug:log
      input:
        message: ${{ steps['fetch-catalog-api'].output.entity | dump }}


    - action: debug:log
      id: write-workspace-directory
      name: List the workspace directory with file contents
      input:
        listWorkspace: with-contents

    - id: publish
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        allowedOrganizations: ['thio-jgmpn']
        description: ${{ parameters.description }}
        repoUrl: github.com?repo=${{ parameters.repoName }}&owner=${{parameters.organization}}
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'


  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }} # link to the remote repository
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
    text:
      - title: API definition
        content: ${{ steps['fetch-catalog-api'].output.entity.spec.definition }}

