apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ${{ values.repoName }}-pipelinerun-
  name: ${{ values.repoName }}-pipelinerun-
  namespace: app-team-b
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    backstage.io/kubernetes-id: ${{ values.repoName }}
  labels:
    tekton.dev/pipeline: ${{ values.repoName }}-pipeline
    type: pipeline
    app: ${{ values.repoName }}
spec:
  params:
    - name: source-repo
      value: 'https://github.com/thio-jgmpn/probeercicdB.git'
    - name: source-branch
      value: main
    - name: output-image
      value: image-registry.openshift-image-registry.svc:5000/app-team-b/probeercicdb
  pipelineRef:
    name: ${{ values.repoName }}-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
