apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: ${{ values.repoName }}-el
  namespace: ${{ values.namespace }}
  annotations:
    backstage.io/kubernetes-id: ${{ values.repoName }}
  labels:
    app: ${{ values.repoName }}
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ['push']
        - ref:
            name: cel
          params:
            - name: git-revision
              value: >-
                (body.ref.contains('main'))
            - name: overlays
              value: null
      template:
        ref: ${{ values.repoName }}-run-pipeline
